import React, { useEffect, useMemo, useState } from 'react';
import { RefreshCw, ShoppingBag, TrendingUp, Sparkles } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { getTopProducts, getTrendingProducts } from '../../services/recommendationApi';
import RecommendationCard from './RecommendationCard';

const SmartRecommendations = () => {
  const [activeTab, setActiveTab] = useState('bestSellers');
  const [bestSellers, setBestSellers] = useState([]);
  const [trending, setTrending] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [isRefreshing, setIsRefreshing] = useState(false);

  const fetchRecommendations = async () => {
    setLoading(true);
    setIsRefreshing(true);
    setError('');

    try {
      const [topProducts, trendingProducts] = await Promise.all([
        getTopProducts(10),
        getTrendingProducts(10),
      ]);
      setBestSellers(topProducts);
      setTrending(trendingProducts);
    } catch (err) {
      setError('Recommendation API is unavailable. Please check the backend connection.');
    } finally {
      setLoading(false);
      setTimeout(() => setIsRefreshing(false), 500); // For animation
    }
  };

  useEffect(() => {
    fetchRecommendations();
  }, []);

  const activeProducts = useMemo(
    () => (activeTab === 'bestSellers' ? bestSellers : trending),
    [activeTab, bestSellers, trending],
  );

  return (
    <motion.section 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: "easeOut" }}
      className="relative overflow-hidden rounded-2xl bg-white/70 backdrop-blur-xl border border-white/50 shadow-[0_8px_32px_rgba(0,0,0,0.05)] p-6 md:p-8"
    >
      {/* Decorative gradient orb */}
      <div className="absolute -top-24 -right-24 w-48 h-48 bg-gradient-to-br from-blue-400/20 to-purple-500/20 rounded-full blur-3xl pointer-events-none" />

      <div className="relative flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-4 h-4 text-amber-500" />
            <span className="text-xs font-bold tracking-wider text-amber-600 uppercase bg-amber-50 px-2 py-1 rounded-full">
              Smart Intelligence
            </span>
          </div>
          <h2 className="text-2xl font-extrabold text-slate-800 tracking-tight">
            Curated For You
          </h2>
          <p className="text-sm text-slate-500 mt-1 font-medium">
            Discover top performers and trending items generated by our AI engine.
          </p>
        </div>

        <motion.button 
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          className="group flex items-center gap-2 bg-white hover:bg-slate-50 border border-slate-200 text-slate-700 px-4 py-2 rounded-xl text-sm font-semibold shadow-sm transition-colors"
          onClick={fetchRecommendations} 
          disabled={loading}
        >
          <RefreshCw className={`w-4 h-4 text-slate-400 group-hover:text-blue-500 transition-colors ${isRefreshing ? 'animate-spin text-blue-500' : ''}`} />
          Refresh Data
        </motion.button>
      </div>

      <div className="relative inline-flex p-1 bg-slate-100/80 backdrop-blur-md rounded-xl mb-6 shadow-inner">
        <button
          className={`relative z-10 flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-bold transition-colors ${
            activeTab === 'bestSellers' ? 'text-blue-700' : 'text-slate-500 hover:text-slate-700'
          }`}
          onClick={() => setActiveTab('bestSellers')}
        >
          {activeTab === 'bestSellers' && (
            <motion.div
              layoutId="smart-tab-pill"
              className="absolute inset-0 bg-white rounded-lg shadow-sm"
              transition={{ type: "spring", bounce: 0.2, duration: 0.6 }}
            />
          )}
          <ShoppingBag className="w-4 h-4 relative z-10" />
          <span className="relative z-10">Best Sellers</span>
        </button>
        <button
          className={`relative z-10 flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-bold transition-colors ${
            activeTab === 'trending' ? 'text-emerald-700' : 'text-slate-500 hover:text-slate-700'
          }`}
          onClick={() => setActiveTab('trending')}
        >
          {activeTab === 'trending' && (
            <motion.div
              layoutId="smart-tab-pill"
              className="absolute inset-0 bg-white rounded-lg shadow-sm"
              transition={{ type: "spring", bounce: 0.2, duration: 0.6 }}
            />
          )}
          <TrendingUp className="w-4 h-4 relative z-10" />
          <span className="relative z-10">Trending Now</span>
        </button>
      </div>

      {error && (
        <motion.div 
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: 'auto' }}
          className="mb-6 p-4 bg-red-50 border border-red-100 rounded-xl text-red-600 text-sm font-medium flex items-center gap-3"
        >
          <div className="w-2 h-2 rounded-full bg-red-500 animate-pulse" />
          {error}
        </motion.div>
      )}

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
        <AnimatePresence mode="wait">
          {loading ? (
            Array.from({ length: 4 }).map((_, i) => (
              <motion.div
                key={`skeleton-${i}`}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="h-[280px] rounded-2xl bg-gradient-to-r from-slate-100 via-slate-50 to-slate-100 bg-[length:200%_100%] animate-[pulse_2s_ease-in-out_infinite] border border-white"
              />
            ))
          ) : activeProducts.length > 0 ? (
            activeProducts.slice(0, 4).map((product, index) => (
              <RecommendationCard
                key={product.productId || product._id || `${activeTab}-${index}`}
                product={product}
                rank={index + 1}
                variant={activeTab === 'trending' ? 'trending' : 'seller'}
                index={index}
              />
            ))
          ) : (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="col-span-full py-12 flex flex-col items-center justify-center text-slate-400 bg-white/40 rounded-2xl border border-dashed border-slate-200"
            >
              <ShoppingBag className="w-12 h-12 mb-3 opacity-20" />
              <p className="font-medium">No recommendations found at the moment.</p>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.section>
  );
};

export default SmartRecommendations;
